version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-east-2)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t lypht:latest .
      - docker tag lypht:latest 810089796778.dkr.ecr.us-east-2.amazonaws.com/lypht:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 810089796778.dkr.ecr.us-east-2.amazonaws.com/lypht:latest

