apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "java-prototype.fullname" . }}
  labels:
    app: {{ template "java-prototype.name" . }}
    chart: {{ template "java-prototype.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "java-prototype.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "java-prototype.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if .Values.localDevEnvironment }}
            - name: JAVAPROTOTYPE_MYSQL_CONNECTION_STRING
              value: "jdbc:mysql://localhost:3306/java_prototype"
            {{- else }}
            - name: JAVAPROTOTYPE_MYSQL_CONNECTION_STRING
              value: {{  .Values.conn }}
            {{- end }}
            - name: JAVAPROTOTYPE_MYSQL_CONNECTION_STRING
              value: {{ .Values.env.conn }}
            - name: JAVAPROTOTYPE_MYSQL_CONNECTION_USER
              value: {{ .Values.env.user }}
            - name: JAVAPROTOTYPE_MYSQL_CONNECTION_PASS
              value: {{ .Values.env.pass }}
            - name: JAVA_OPTS
              value: {{ .Values.env.javaopts }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     host: 127.0.0.1
          #     port: http
          #   initialDelaySeconds: 120
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     host: 127.0.0.1
          #     port: http
          #   initialDelaySeconds: 120
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
